# Syntax reference:
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions
name: Lint Checks

on:
  push:
    branches: main
  pull_request:
    branches: main

env:
  CARGO_TERM_COLOR: always

jobs:
  format:
    name: Check code formatting

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Rust toolchain
      run: rustup toolchain install
    - name: Check Rust version
      run: cargo --version && rustc --version
    - name: Add rustfmt
      run: rustup component add rustfmt
    - name: Check Rust format
      run: cargo fmt -- --check
    # Gives us extra features for organizing imports
    - name: Add rustfmt nightly
      run: rustup +nightly component add rustfmt
    - name: Check Rust format nightly
      run: cargo +nightly fmt -- --config-path rustfmt-nightly.toml --check

  clippy:
    name: Check clippy warnings

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Rust toolchain
      run: rustup toolchain install
    - name: Check Rust version
      run: cargo --version && rustc --version
    - name: Add clippy
      run: rustup component add clippy
    - name: Check clippy
      run: cargo clippy --all-targets -- -Dwarnings
